### ISSUE TITLE
Blogs/Store/Ads: post thumbnail is too blurry for Outline

### ISSUE THREAD

**Issue by AlexTr** [boonex/dolphin.pro#131]
https://www.boonex.com/forums/topic/blog-thumnail-not-compatible-for-outline-.htm

The same problem is for Store and Ads thumbnail in Outline

**Comment by AntonLV** [comment]
The issue was fixed for Blogs module in Ticket #116

**Comment by AntonLV** [comment]
Re: Store and the other modules which use Photos module to process photo uploading. 
In this case the problem is in the Photos module. It creates big image from small one during resizing. For example, I used small image (64*64) during Store Product creation. Photos module generated full set of images where "browse" image has 240*240 dimensions and so on. In this case Outline can do nothing if it receives an "appropriate" image with 240*240 dimensions but with pure quality.

**Comment by AlexTr** [comment]
It isn't good to load original photo size even for normal sizes, it still ok for retina I think! 
So I would suggest to implement new size in Blogs for normal thumb - 240xAUTO (set height to null), there is already iBigThumbSize, but it isn't used, for compatibility with old versions - use smaller image, if this one isn't exist
