### ISSUE TITLE
Payment issues

### ISSUE THREAD

**Issue by kisonik** [boonex/dolphin.pro#143]
Payment issues: no BitPay on Join, free memberships (price 0) still get processed through a payment provider.

Related issue - #139

**Comment by AlexTr** [comment]
@AntonLV  please post notification here as soon as this problem is fixed - https://app.intercom.io/a/apps/ss0u2e8q/inbox/dev@boonex.com/conversations/1351876397

**Comment by bankstas** [comment]
(1) My Bitpay doesnt checkout in the join proces and (2) my free level members are being forced to through the paypal process. In relaton to the membership issue: MEMBERSHIPS 
Levels	Add Level	Settings 
System Levels 
Non-member Actions 
Standard Actions 
Promotion Actions.. 
ad interim, to resolve the issue of my free membership levels being forced to paypal process; is there anyway to just extend the system level free membership levels (ad interim) so that i could direct my visitors who are only interested in free membership to the system's free levels memberships. and how do visitors reach the "standard" level

**Comment by AntonLV** [comment]
RE 1: BitPay is not available for "Pay Before Join" mode, because it has delayed payment processing. Therefore only PayPal and 2Checkout from default Payment module are available for "Pay Before Join" mode.

**Comment by bankstas** [comment]
this is not totally responsive to my last support inquries. Right now I
think its I need to ask about refund and charge back policies questions.

**Comment by bankstas** [comment]
Oh this is not boonex its github. Pardon me. Ive been waiting for hours etc
for boonex responses

**Comment by AntonLV** [comment]
RE 2: The enhancement was done. You may check it in Ticket #172 (Payment before join: need a way to join without payment for free membership)
