### ISSUE TITLE
Payment before join: need a way to join without payment for free membership

### ISSUE THREAD

**Issue by AlexTr** [boonex/dolphin.pro#172]
1. If price for membership is 0, then it shouldn't redirect to payment provider, but just join user with this free membership. Also it would be great to display price as "Free" instead "0 USD" for free membership levels.
2. Alternative variant is: add option in Membership module to show/hide Standard membership level in membership level select form when "Pay Before Join" feature is enabled.

**Comment by bankstas** [comment]
MEMBERSHIPS 
Levels	Add Level	Settings 
System Levels 
Non-member Actions 
Standard Actions 
Promotion Actions.. to resolve the issue of my free membership levels being forced to paypal process; is there anyway to just extend the system level free membership levels (ad interim) so that i could direct my visitors who are only interested in free membership to the system's free levels memberships. and how do visitors reach the "standard" level

**Comment by AntonLV** [comment]
need to post notification here as soon as this enhancement is finished
https://app.intercom.io/a/apps/ss0u2e8q/inbox/dev@boonex.com/conversations/1351876397
