### ISSUE TITLE
Improvements in getSiteInfo function

### ISSUE THREAD

**Issue by AlexTr** [boonex/dolphin.pro#191]

**Comment by launch3** [comment]
I made the changes to utils.inc.php.
Now it shows the domain url instead of article/page titles.
(example below).
I undid the above changes to my utils file.
Will wait for an update to this before re-trying.

![utils_inc_php-changes](https://cloud.githubusercontent.com/assets/13964338/11251524/a9ac94c8-8dff-11e5-84e8-724463f68001.png)

**Comment by launch3** [comment]
Including a thumbnail image with each link would be awesome.

**Comment by AlexTr** [comment]
Thank you @launch3 for quick testing!

We are working on fetching thumbnail for a URL in Trident now, later we will try to implement it in Dolphin as well.
