### ISSUE TITLE
[Planning] Thoughts on using composer for autoloading.

### ISSUE THREAD

**Issue by Prashank25** [boonex/dolphin.pro#262]
Hello,

I have been putting some effort to modernize the codebase and its quite painful with all those notices and deprecation warning but I did a lot of updates and its a bit better. Right now its a big mess of require statements. So what are the developer's thoughts on using composer to autoload the classes and manage the dependencies (if we use composer than why not)? It would mean more cleaner structure. There would be some breaking changes but it will be worth it in the long run. Thoughts?

Also, php7 is out for some time now, what's the choice for mysql replacement, PDO or MySQLi?

Note, that I am taking about a very later version here, whatever seems good to the owners of this water mammal.

**Comment by AlexTr** [comment]
Usually when package is loaded using composer then the whole package is downloaded (with test, samples, etc) which isn;'t required for productions sites. Also some packages requires custom downloading (TinyMCE, jQuery UI, some others) which isn't working with composer. So we used old system - when proper package is downloaded and not required files are deleted, so it makes Dolphin zip much smaller in size and no any unnecessary files are stored.

Also we implemented autoloading in Trident and get rid of any notices and warnings, it required a lot of structural changes, which will make upgrade very painful since almost every file need to be changed.

Most probably we will go with PDO in future versions.
