### ISSUE TITLE
New Default Privacy Settings Have No Effect on New Members/Albums

### ISSUE THREAD

**Issue by toxalot** [boonex/dolphin.pro#312]
#165 adds the option to set site-wide privacy defaults, but I don't see what this really does. I would expect that if I set the default for profiles to Members and the default for photos to Friends that the following would happen:

1) new members would be created with Profiles.allow_view_to = 4 (not 3)
2) Members (not Public) would be pre-selected when clicking the key on a profile block, unless it's already set to something else
3) default photo albums would be created with sys_albums.AllowAlbumView = 5 (not 3)
4) Friends (not Public) would be pre-selected in the privacy drop-down when creating a new photo album

For item 1, the easiest solution is probably to alter the table when the setting is changed and update the default used for Profiles.allow_view_to and Profiles.PrivacyDefaultGroup.

**Comment by toxalot** [comment]
@AlexTr 1, 3, and 4 are fixed. However, item 2 is still an issue.

**Comment by AlexTr** [comment]
2. It's should be always public, since there is separate privacy option for profile on profile edit page, to hide all blocks, if this options will not be public it will interfere with another setting. Later user can change it to any setting but by default it should be public. I believe that this is correct behaviour.

**Comment by toxalot** [comment]
OK
