### ISSUE TITLE
Dont use this Fake "Open Source"

### ISSUE THREAD

**Issue by Squillynet** [boonex/dolphin.pro#510]
I would warn to use Boonex whit a License.
after i have buyed a Monthly Licens an wrote Boonex that i dont whish a new, they have booked 29$ again, whitout my ok.

For the first License i made a PayPal Case and got my monex back, but the second (Illegal transfer) would be made. No i have to Fight to get my Money back.

If you have any Problems whit the script the sugestion from the "Support" in most cases is "Buy a module from te market". The main reason from Dolphin is not to give Users the posibility to make good Communitys, the main reason ist to grab the Users Money.

**Comment by tchbnl** [comment]
You can cancel your subscription at any time from your BoonEx account, or contact support for a cancellation. A PayPal dispute is never needed, nor should it ever be your first choice.

Not everything can be done in core Dolphin. So if a needed feature doesn't exist but is available in the market, it's likely you'll be referred to that - why reinvent the wheel? You can also have the feature implemented with custom work, but BoonEx can't do this for you. Also, BoonEx doesn't receive any cut from market sales - it's all sent directly to the vendor via their own PayPal account.

But this is all off-topic. This is GitHub, and anything here is to discuss Dolphin development.

**Comment by Squillynet** [comment]
ok, a questin to the "Development"
Why do you encrypt the Lambda Funktion created your Licens System?
at first, this makes the Script very slow.
at second. Tihs makes the Script to a non Open Scource.

And i it right that your aoutsourced som Parts of the Scripts to your owen Servers?
And if thi ist true, what are you doing there? I would like to see what you are doing there because ist "open Source" ;)

**Comment by tchbnl** [comment]
I'm not a BoonEx developer, but I am a contributor.

The license code is Base64-encoded to prevent easy modification and circumvention. It doesn't slow the script down (unless maybe you're running Dolphin on a toaster, but then you have more problems than the license code), and fits fine with the CC-BY license Dolphin is under. No actual code somebody would ever need to touch is encoded.

Here's what Dolphin sends to BoonEx servers:

* License to check if it's valid (this happens only when the license is entered) (only encoded bit). BoonEx records the license and domain to tie to two together. That's the only info about a site they know about for certain - no data like members, etc. are ever sent over. You can easily check the code to confirm that.
* Version of the site: There's a version check in the header that shows if an update is available. So BoonEx could see the version sent, which is needed to see if it's up-to-date. You can remove the code.

Go ahead and decode the Base64 bits and check it out. Nobody is going to jump down from attack helicopters and swarm your house.

**Comment by Squillynet** [comment]
> Here's what Dolphin sends to BoonEx servers:

This is what you say, but is this what it sends?
on the first Page you are offeringt Dolphin as OPEN SOURCE, but Parts are encryptet or on your servers. THIS IS NOT OPEN SOURCE.
How can useres improve what Dolphin sends to you?

p.s. 
before i deleted Dolphin form my server i edited the Lambda Function, and the script was about 15% faster. May be it would be better if this discus would made by a Developer.
As you said:

> This is GitHub, and anything here is to discuss Dolphin development.

**Comment by tchbnl** [comment]
> This is what you say, but is this what it sends?
> on the first Page you are offeringt Dolphin as OPEN SOURCE, but Parts are encryptet or on your servers. THIS IS NOT OPEN SOURCE.
> How can useres improve what Dolphin sends to you?

Yes, Dolphin isn't under an OSI-approved license. But for all intents and purposes, the code is open - it's on GitHub. without NDAs or other nasty legal things. Yes, some bits are Base64-encoded, but not encrypted. Like I said, feel free to decode it and take a look at it. But there is literally no functionality in there a user should ever touch - it only controls the license check and to show the banner, and that's a part of the attribution requirement in the CC license. If you do "null" Dolphin, keep it to yourself and be cool and buy a license.

Dolphin sends BoonEx the license if entered, and BoonEx tells Dolphin if the license is valid. If the license is valid, Dolphin flips a switch of sorts and turns off the license banner. If no license is entered, it stays in free trial mode and BoonEx never hears from it. That's the only bit that's encoded (the license system). You never need to touch or change it, because part of the free mode means the banner is there. And on a license site, it doesn't show at all. But like I said above...

**Comment by tchbnl** [comment]
> This is what you say, but is this what it sends?
> on the first Page you are offeringt Dolphin as OPEN SOURCE, but Parts are encryptet or on your servers. THIS IS NOT OPEN SOURCE.
> How can useres improve what Dolphin sends to you?

Yes, Dolphin isn't under an OSI-approved license. But for all intents and purposes, the code is open - it's on GitHub. without NDAs or other nasty legal things. Yes, some bits are Base64-encoded, but not encrypted. Like I said, feel free to decode it and take a look at it. But there is literally no functionality in there a user should ever touch - it only controls the license check and to show the banner, and that's a part of the attribution requirement in the CC license. If you do "null" Dolphin, keep it to yourself and be cool and buy a license.

Dolphin sends BoonEx the license if entered, and BoonEx tells Dolphin if the license is valid. If the license is valid, Dolphin flips a switch of sorts and turns off the license banner. If no license is entered, it stays in free trial mode and BoonEx never hears from it. That's the only bit that's encoded (the license system). You never need to touch or change it, because part of the free mode means the banner is there. And on a license site, it doesn't show at all. But like I said above...

**Comment by Squillynet** [comment]
> If you do "null" Dolphin, keep it to yourself and be cool and buy a license.

Yes i have "Nulled" Dolphin, but i have only tested and saw that is faster. Because of this i cant belive that this what you said is all. After i have tested tghe "Nulled" Dolphin, i deleted the hole Script an didnt use it anymore.

Other "Costumers" which use a "Nulled" Dolphin, sure wouldt delet their script and "be cool" and by a license.

Why do you not offer a version which is realy Open? Make some limits and keep out the fucking "Licens-System and outsourced Parts.
Because of your Practise whit the "Open Scours", the Billing and Paiment, i cant trust Boonex. And so i cant Dolphin trust if i cant see what it makes.
Maybe its illegal in germany what you ar doing whit the informations of my useres? How should i know this?

**Comment by tchbnl** [comment]
> Maybe its illegal in germany what you ar doing whit the informations of my useres? How should i know this?

BoonEx doesn't know anything about your site's users. All it knows is the license and what domain it's attached to. It couldn't tell you the time of day for your site.

> Why do you not offer a version which is realy Open? Make some limits and keep out the fucking "Licens-System and outsourced Parts.

Sure. Take a look at UNA. You can use the free core and then buy all the nice features from Dolphin as separate modules. Dolphin is as full-featured as it is because there's a license system. And most people are fine with a license or a banner if it means they have a script with all these awesome features for free (banner) or a one-time fee (license).
