### ISSUE TITLE
Problem with HTTPS & Timeline Link Images

### ISSUE THREAD

**Issue by launch3** [boonex/dolphin.pro#514]
I've converted all my Dolphin websites to SSL/https.
Just about everything works great.
But ...1 problem.

When members post links to the timeline, there's a problem with the image posted for that link.

EITHER
I get a "mixed content" error message and the page is no longer considered secure (but each link image does display),
OR
if I add something like < meta http-equiv="Content-Security-Policy" content="upgrade-insecure-requests" > to my header file so the site is secure, the image for each posted link no longer appears (image below).

![ssl-timeline-link-images-not-displaying](https://cloud.githubusercontent.com/assets/13964338/21317593/c52dbaa8-c5d3-11e6-8b04-c8a096bf10ef.png)

Either way, it's an issue.
How to fix?

**Comment by AlexTr** [comment]
```
        $aHeaders = get_headers($sUrl);
        $sContent = bx_file_get_contents($sUrl);
        
        foreach ($aHeaders as $sHeader) {
            $aMatches = array();
            if(preg_match("/^Cache-Control:\s*max-age\s*=\s*([0-9]*)$/i", $sHeader, $aMatches)) 
                if((int)$aMatches[1] < 2592000)
                    $sHeader = 'Cache-Control: max-age=2592000';
        
            header($sHeader);
        }
```
1. Always send `'Cache-Control: max-age=2592000';` header when sending image from Timeline
2. Look through original image headers to detect if it's really an image by `Content-Type` header (instead of detecting by extension like in the previous implementation)
3. Read original image file content after it was identified as an image
