### ISSUE TITLE
Bug in execSqlFile method

### ISSUE THREAD

**Issue by AlexTr** [boonex/dolphin.pro#674]
https://www.boonex.com/forums/topic/Error-with-new-dolphin-7-4-0-BxDolExceptionHandler.htm

**Comment by manadi** [comment]
Because security reasons, some hosting limits the script function for "readfile ()" it causes the Image we upload cannot be loaded, as a solution the script is changed to "echo file_get_contents ()", in the file "modules/boonex/photos/classes/BxPhotosModule.php" and
"inc/classes/BxDolTwigModule.php", so the image can be loaded properly, but i do not know if the replacement of the script will affect to other functions.

**Comment by AlexTr** [comment]
https://github.com/boonex/dolphin.pro/issues/675
